Ashish_P_301089716/Models/Clubs.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Ashish_P_301089716.Models
{
    public class Clubs
    {

        [Key]
        public int ClubId { get; set; }
        public string NameOfClub { get; set; }
        public string NameOfCoach { get; set; }
        public int StadiumCapacity { get; set; }
        public int NumberOfPlayers { get; set; }
        public string President { get; set; }
        public string LeagueParticipated { get; set; }

        public ICollection<Player> Players { get; set; }

      
    }

  
}

Ashish_P_301089716/Controllers/CRUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ashish_P_301089716.Models;
using Microsoft.AspNetCore.Mvc;

namespace Ashish_P_301089716.Controllers
{
    public class CRUDController : Controller
    {
        IClubRepository clubrepository;

        public CRUDController(IClubRepository repo)
        {
            clubrepository = repo;
        }
        public ViewResult UpdateClub(int clubId)
        {
            return View(clubrepository.Clubs.FirstOrDefault(a => a.ClubId == clubId));
        }

        [HttpPost]
        public IActionResult UpdateClub(Clubs clubs)
        {
            clubrepository.UpdateClub(clubs);
            return RedirectToAction("ManageClubs",new {cludId = clubs.ClubId });
        }

        public RedirectToActionResult DeleteClub(int clubId)
        {
            Clubs dclub = clubrepository.DeleteClub(clubId);
            if (dclub != null)
            {
                TempData["message"] = $"{dclub.NameOfClub} has been deleted!";
            }
            return RedirectToAction("Clubs");
        }

    }
}

Ashish_P_301089716/Controllers/ClubsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ashish_P_301089716.Models;
using Microsoft.AspNetCore.Mvc;

namespace Ashish_P_301089716.Controllers
{
    public class ClubsController : Controller
    {
        IClubRepository repository;
        public ClubsController(IClubRepository clubRepository)
        {
            repository = clubRepository;
        }
        public ViewResult Clubs()
        {
            return View(repository.Clubs);
        }

        public ViewResult ManageClubs(int clubID)
        {
            return View(repository.Clubs.FirstOrDefault(o=>o.ClubId == clubID));
        }

        public ViewResult AddClubPage()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddClubPage(Clubs clubs)
        {
            repository.AddClub(clubs);
            return RedirectToAction(nameof(Clubs));
        }

        public ViewResult UpdateClub(int clubId)
        {
            return View(repository.Clubs.FirstOrDefault(a => a.ClubId == clubId));
        }
        
    }
}

Ashish_P_301089716/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ashish_P_301089716.Models;
using Microsoft.AspNetCore.Mvc;

namespace Ashish_P_301089716.Controllers
{
    public class PlayersController : Controller
    {
        IPlayerRepository repository;
        IClubRepository crepos;
        public PlayersController(IPlayerRepository repo, IClubRepository repos)
        {
            repository = repo;
            crepos = repos;
        }
        public ViewResult ManagePlayers(Player player)
        {
            ViewData["clubs"] = crepos.Clubs;
            
            return View(repository.Players);
        }

        [HttpPost]
        public IActionResult AssignClubtoPlayer(int clubId, int playerId)
        {
            repository.UpdatePlayer(playerId, clubId);
            return RedirectToAction("ManagePlayers", new { player = repository.Players.FirstOrDefault(a=>a.PlayerId == playerId)});
            
        }
    }
}

Ashish_P_301089716/Views/Clubs/AddClubPage.cshtml
@{
    ViewData["Title"] = "AddClub";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 class="title add-club">Want to Add a Club?</h1>
@Html.Partial("_AddClubForm");

Ashish_P_301089716/Views/Clubs/Clubs.cshtml
@model IEnumerable<Clubs>
    <div class="grid-container">
        @foreach (var club in Model)
        {
            <section>
                <div class="content">
                    <header>
                        <div class="image-shadow">
                            <img src="~/images/FC_Barcelona.png" style="width:200px;height:200px; border-radius:10px" />
                        </div>
                        <h2>Club: @club.NameOfClub</h2>
                    </header>
                    <h4>Head coach: @club.NameOfCoach</h4>

                    <a class="button" style="height:45px; width:135px; position:center; background-color:#2bb0d9;" asp-action="ManageClubs" asp-route-clubID="@club.ClubId">
                        <span>Details</span>
                    </a>

                </div>
            </section>
        }
    </div>

Ashish_P_301089716/Views/Clubs/ManageClubs.cshtml
@model Clubs
    
    <div class="grid-container " style="width: 500px; " >

        <section class="col-2" >
            <div class="content">
                <header>
                    <div class="image-shadow">
                        <img src="~/images/FC_Barcelona.png" style="width:200px;height:200px; border-radius:10px" />
                    </div>
                    <h2>Club: @Model.NameOfClub</h2>
                </header>
                <h4>Head coach: @Model.NameOfCoach</h4>
                <h4>Stadium Capacity: @Model.StadiumCapacity</h4>
                <h4>Number Of Players: @Model.NumberOfPlayers</h4>
                <h4>President: @Model.President</h4>
                <h4>Leagues: @Model.LeagueParticipated</h4>
                <h4>Players</h4>
                <ul>

                    @foreach (var v in Model.Players)
                    {
                        <li><h4 style="margin-block-start: -16px;">@v.Name</h4></li>
}
                </ul>

                <a class="button" style="height:45px; width:80px; background-color:#46c768;" asp-action="UpdateClub" asp-route-clubId="@Model.ClubId" asp-controller="CRUD">
                    <span>Edit</span>
                </a>
                <a class="button" style="height:45px; width:80px;" asp-action="DeleteClub" asp-controller="CRUD" asp-route-clubId="@Model.ClubId">
                    <span>Delete</span>
                </a>
                <a class="button" style="height:45px; width:100px;" asp-action="ManagePlayers" asp-controller="Players">
                    <span>Manage Players</span>
                </a>
            </div>
        </section>
        </div>
        
                

            