Ashish_P_301089716/Controllers/ClubsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ashish_P_301089716.Models;
using Microsoft.AspNetCore.Mvc;

namespace Ashish_P_301089716.Controllers
{
    public class ClubsController : Controller
    {
        IClubRepository repository;
        public ClubsController(IClubRepository clubRepository)
        {
            repository = clubRepository;
        }
        public ViewResult Clubs()
        {
            return View(repository.Clubs);
        }

        public ViewResult ManageClubs(int clubID)
        {
            return View(repository.Clubs.FirstOrDefault(o=>o.ClubId == clubID));
        }

        public ViewResult AddClubPage()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddClubPage(Clubs clubs)
        {
            repository.AddClub(clubs);
            return RedirectToAction(nameof(Clubs));
        }

        public ViewResult UpdateClub(int clubId)
        {
            return View(repository.Clubs.FirstOrDefault(a => a.ClubId == clubId));
        }
        
    }
}

Ashish_P_301089716/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ashish_P_301089716.Models;
using Microsoft.AspNetCore.Mvc;

namespace Ashish_P_301089716.Controllers
{
    public class PlayersController : Controller
    {
        IPlayerRepository repository;
        IClubRepository crepos;
        public PlayersController(IPlayerRepository repo, IClubRepository repos)
        {
            repository = repo;
            crepos = repos;
        }
        public ViewResult ManagePlayers(Player player)
        {
            ViewData["clubs"] = crepos.Clubs;
            
            return View(repository.Players);
        }

        [HttpPost]
        public IActionResult AssignClubtoPlayer(int clubId, int playerId)
        {
            repository.UpdatePlayer(playerId, clubId);
            return RedirectToAction("ManagePlayers", new { player = repository.Players.FirstOrDefault(a=>a.PlayerId == playerId)});
            
        }
    }
}

Ashish_P_301089716/Views/Shared/_AddClubForm.cshtml
@model Clubs


<head>
    <script src="~/js/Js.js"></script>
    <link href="~/css/menu.css" rel="stylesheet" />
</head>

<div>
    <section class="add-club">
        
        <form asp-action="AddClubPage" asp-controller="Clubs" method="post" class="club-form row">

            <div class="form-field col-lg-6">
                <input class="input-text" type="text" asp-for="NameOfClub" placeholder="Name of Club" required>
                <label class="label"></label>
            </div>
            <div class="form-field col-lg-6 ">
                <input class="input-text" type="text" asp-for="NameOfCoach" placeholder="Name of Coach" required>
                <label class="label"></label>
            </div>
            <div class="form-field col-lg-6 ">
                <input class="input-text" type="text" asp-for="StadiumCapacity" placeholder="Stadium Capacity" required>
                <label class="label"></label>
            </div>
            <div class="form-field col-lg-6 ">
                <input class="input-text js-input" type="text" asp-for="NumberOfPlayers" placeholder="Numbers of Players" required>
                <label class="label"></label>
            </div>
            <div class="form-field col-lg-6">
                <input class="input-text js-input" type="text" asp-for="President" placeholder="President" required>
                <label class="label"></label>
            </div>
            <div class="form-field col-lg-6">
                <input class="input-text js-input" type="text" asp-for="LeagueParticipated" placeholder="Leagues Participated." required>
                <label class="label"></label>
            </div>

            <div class="form-field col-lg-12">
                <input class="button" type="submit" value="Save">
            </div>
            <div class="form-field col-lg-12">
                <a class="button" asp-action="Index" asp-controller="Home">Cancel</a>
            </div>
        </form>
    </section>
</div>

Ashish_P_301089716/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/menu.css" rel="stylesheet" />
    <script src="~/js/Js.js"></script>
</head>
<body class="bgaddclub">
    <div>
        <div class="navbar">
            <a class="btn btn-primary" asp-action="Index" asp-controller="Home">Home</a>
            <a class="btn btn-primary" asp-action="Clubs" asp-controller="Clubs">Clubs</a>
            <a class="btn btn-primary" asp-action="ManagePlayers" asp-controller="Players">Players</a>
            <a class="btn btn-primary" asp-action="AddClubPage" asp-controller="Clubs">Add Club</a>
            <a class="btn btn-primary" asp-action="AboutUs" asp-controller="Home">About us</a>
        </div>
        @RenderBody()
    </div>
</body>
</html>